name: Type check, Lint and Test

 on: [push]

 jobs:
   install-and-test:
     runs-on: ubuntu-latest
     steps: 
       - uses: actions/checkout@v2
       - name: Install npm dependencies
         run: |
           yarn
       - name: Lint
         run: |
           yarn lint
       - name: Test
         run: |
           yarn test 